### ISSUE TITLE
panic: upx failed: fork/exec /usr/bin/upx: no such file or directory

### ISSUE THREAD

**Issue by denji** [pwaller/goupx#15]
We use Homebrew, we have a problem with finding the `$PATH`
It is located at `/usr/local/bin`

```
{Class:ELFCLASS64 Data:ELFDATA2LSB Version:EV_CURRENT OSABI:ELFOSABI_NONE ABIVersion:0 ByteOrder:LittleEndian Type:ET_EXEC Machine:EM_X86_64 Entry:4574880}
File fixed!
upx failed: fork/exec /usr/bin/upx: no such file or directory
panic: upx failed: fork/exec /usr/bin/upx: no such file or directory

goroutine 1 [running]:
log.Panic(0xc82003fe18, 0x2, 0x2)
	/usr/local/Cellar/go/HEAD/libexec/src/log/log.go:320 +0xc1
main.compressBinary(0x7fff5fbff9ee, 0x1b, 0xc820074290, 0x1, 0x1)
	/Users/denji/Code/Go/src/github.com/pwaller/goupx/main.go:61 +0x30e
main.main()
	/Users/denji/Code/Go/src/github.com/pwaller/goupx/main.go:91 +0x13e
```

```
$  which upx
/usr/local/bin/upx
$ upx --version
upx 3.92
UCL data compression library 1.03
LZMA SDK version 9.38 beta
Copyright (C) 1996-2015 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2015 Laszlo Molnar
Copyright (C) 2000-2015 John F. Reiser
Copyright (C) 2002-2015 Jens Medoch
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```

**Comment by pwaller** [comment]
Fixed in #14, I believe. Comment if not.
