### ISSUE TITLE
win32 is not supported (using upx391w)

### ISSUE THREAD

**Issue by shawnye** [pwaller/goupx#17]
<pre>
D:\dev\workspace\go\src>goupx hello.exe
2016/03/10 10:31:59 Failed to parse ELF. This can happen if the binary is alread
y packed.
2016/03/10 10:31:59 Failed to fix 'hello.exe': bad magic number '[77 90 144 0]'
in record at byte 0x0
panic: Failed to fix 'hello.exe': bad magic number '[77 90 144 0]' in record at
byte 0x0

goroutine 1 [running]:
panic(0x508880, 0x1182e1f0)
        D:/dev/go1.6/src/runtime/panic.go:464 +0x326
log.Panicf(0x563130, 0x16, 0x11841f04, 0x2, 0x2)
        D:/dev/go1.6/src/log/log.go:327 +0xb5
main.runHemfix(0x1181a110, 0x9)
        D:/dev/workspace/go/src/github.com/pwaller/goupx/main.go:92 +0x147
main.main()
        D:/dev/workspace/go/src/github.com/pwaller/goupx/main.go:101 +0xae
</pre>

**Comment by pwaller** [comment]
Hi! Thanks for filing this. As far as I know, the problem solved by `goupx` is only relevant to windows binaries. `upx hello.exe` should work just fine without `goupx`. Please comment to let me know if that's not the case.

`goupx` anyway is only currently designed to work on Linux binaries prior to go1.6. With go1.6 and later the go compiler itself fixes the problem.
