### ISSUE TITLE
Does not pack arm64 executables

### ISSUE THREAD

**Issue by sokoow** [pwaller/goupx#20]
When I try to pack arm64 executable:

```
root@8302c6333c99:/opt/go/bin# ./goupx promu 
2016/07/10 13:06:53 {Class:ELFCLASS64 Data:ELFDATA2LSB Version:EV_CURRENT OSABI:ELFOSABI_NONE ABIVersion:0 ByteOrder:LittleEndian Type:ET_EXEC Machine:EM_ALPHA_STD+142 Entry:4195720}
2016/07/10 13:06:53 File fixed!
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: promu: UnknownExecutableFormatException

Packed 0 files.
2016/07/10 13:06:53 upx failed: exit status 1
panic: upx failed: exit status 1

goroutine 1 [running]:
panic(0x135260, 0x482000f9c0)
    /usr/lib/go-1.6/src/runtime/panic.go:481 +0x384
log.Panic(0x4820089e00, 0x2, 0x2)
    /usr/lib/go-1.6/src/log/log.go:320 +0xc0
main.compressBinary(0x7fc448190d, 0x5, 0x482000e3f0, 0x1, 0x1)
    /opt/go/src/github.com/pwaller/goupx/main.go:72 +0x358
main.main()
    /opt/go/src/github.com/pwaller/goupx/main.go:103 +0xe8
```

**Comment by pwaller** [comment]
Yes, unfortunately it looks like UPX does not support this format at all. UPX does support AMD64, but Go used to produce binaries that it could not pack. Goupx fixes that problem only. It does not implement a packer itself. Sorry.
