### ISSUE TITLE
bug 	/root/go/src/github.com/pwaller/goupx/main.go:103 +0xf5

### ISSUE THREAD

**Issue by hktalent** [pwaller/goupx#21]
```
#/bin/goupx -s -w gsnova_linux
2019/01/08 20:56:32 {Class:ELFCLASS64 Data:ELFDATA2LSB Version:EV_CURRENT OSABI:ELFOSABI_NONE ABIVersion:0 ByteOrder:LittleEndian Type:ET_EXEC Machine:EM_X86_64 Entry:4573824}
2019/01/08 20:56:32 File fixed!
upx: invalid option '-s'
Usage: upx [-123456789dlthVL] [-qvfk] [-o file] file..
2019/01/08 20:56:32 upx failed: exit status 1
panic: upx failed: exit status 1

goroutine 1 [running]:
log.Panic(0xc00006fec8, 0x2, 0x2)
	/usr/lib/go-1.11/src/log/log.go:326 +0xc0
main.compressBinary(0x7ffcc629698b, 0xc, 0xc0000840c0, 0x3, 0x4)
	/root/go/src/github.com/pwaller/goupx/main.go:72 +0x19d
main.main()
	/root/go/src/github.com/pwaller/goupx/main.go:103 +0xf5
```

**Comment by pwaller** [comment]
Hi,

What version of Go and UPX are you using? Note that `goupx` is not necessary for recent versions of go, you can just invoke upx directly.

**Comment by hktalent** [comment]
@pwaller 
```
UPX 3.95
kali linux
#go version
go version go1.11.4 linux/amd64
```

**Comment by pwaller** [comment]
It also looks like you're passing `-s`, which was passed directly to upx, which doesn't have that option, if I'm reading things correctly.
